--Focused on POSTGRE SQL


DROP TABLE IF EXISTS "driverlicenses";
DROP TABLE IF EXISTS "cars";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "users" cascade;


SELECT 'create DATABASE TAXI
      ENCODING UTF8'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'TAXI');

SELECT 'create USER IF NOT EXISTS TAXIADMIN with PASSWORD adminpassword123'
  WHERE NOT EXISTS (SELECT FROM pg_user WHERE pg_user.usename = 'TAXIADMIN');

GRANT ALL PRIVILEGES ON DATABASE "TAXI" to "TAXIADMIN";

create TABLE users (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	password varchar(30),
	firstName varchar(50),
	lastName varchar(50),
	phone varchar(13) unique,
  birthDate varchar(50),
	email varchar(50),
	role varchar(15)
);

create TABLE cars (
	id serial PRIMARY KEY,
	driver int references users(id),
	carNumber varchar(30) unique,
	carName varchar(100),
	category varchar(15),
	capacity int
);

create TABLE orders (
	id serial PRIMARY KEY,
	driver_id int references users(id),
	client_id int references users(id),
	creationDate date,
	startTrip date,
	finishTrip date,
	startingPoint varchar(50) not null,
	finishPoint varchar(50) not null,
	cost int not null,
	feedback varchar(250) ,
	serviceQuality int,
	orderNumber int,
	status varchar(20)
);

INSERT INTO users(id,firstName, lastName, phone,role, email, password)
VALUES(1,'Федор', 'Зотов', '380993785685', 'Administrator', 'examples@goole.com', 'password1');

INSERT INTO users(id, firstName, lastName, phone,  role, email, password)
VALUES(2,'Матвей', 'Ильин', '380993185685', 'Driver', 'examples1@goole.com', 'password1');

INSERT INTO users(id,firstName, lastName, phone,  role, email, password)

VALUES(3, 'Nicolas', 'Cage', '380993725685', 'Driver', 'examples1@goole.com', 'password1');

INSERT INTO users(id,firstName, lastName, phone,  role, email, password)
    VALUES(4, 'IVAN', 'IVANOV', '380993335685', 'Client', 'examples2@goole.com', 'password1');

INSERT INTO users(id,firstName, lastName, phone,  role, email, password)
VALUES(5, 'PETER', 'PETROV', '380993335689', 'Client', 'examples3@goole.com', 'password1');

INSERT INTO users(id,firstName, lastName, phone,  role, email, password)
VALUES(6, 'Андрей', 'Плеханов', '380999435685', 'Client', 'examples4@goole.com', 'password1');

INSERT INTO users(id,firstName, lastName, phone,  role, email, password)
VALUES(7, 'Давид', 'Голиафов', '380993435685', 'Client', 'examples5@goole.com', 'password1');

INSERT INTO users(id,firstName, lastName, phone,  role, email, password)
VALUES(8, 'Василий', 'Кузнецов', '380963437885', 'Client', 'examples6@goole.com', 'password1');

INSERT INTO cars(driver, carNumber, carName,category, capacity)
        VALUES(2, 'AX097A1','Шеврлое Авео', 'Comfort', 4);

INSERT INTO cars(driver, carNumber, carName,category, capacity)
VALUES(3, 'AX807A1','BMW m3', 'Premium', 4);

